name: Test Automation with maven

on:

schedule:

- cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: running test autiomation with Mavenname
      run: mvn test -X -Dbrowser=chrome  -Dislambdatest=true -Disheadless=false
   
    - name: Upload Test logs 
      if: Always()
      uses: actions/upload-artifact@v5.0.0
      with:
      name: Test logs
      path: logs/
      
     - name: Upload Test Reports 
      if: Always()
      uses: actions/upload-artifact@v5.0.0
      with:
      name: Test Reports
      path: Report.html

   - name: Test Execution Status
      run: echo "Test Execution Completed"


    
    
    
    
    
    
    
    
    
    
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
